version: '3.8'

services:
  paypal-proxy:
    build: .
    container_name: paypal-proxy-go
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      # Add your actual environment variables here
      - MAGIC_CONSUMER_KEY=${MAGIC_CONSUMER_KEY}
      - MAGIC_CONSUMER_SECRET=${MAGIC_CONSUMER_SECRET}
      - OITAM_CONSUMER_KEY=${OITAM_CONSUMER_KEY}
      - OITAM_CONSUMER_SECRET=${OITAM_CONSUMER_SECRET}
    env_file:
      - .env
    volumes:
      - ./logs:/var/log/paypal-proxy:rw
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - paypal-proxy-network

  # Optional: Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: paypal-proxy-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - paypal-proxy
    networks:
      - paypal-proxy-network

networks:
  paypal-proxy-network:
    driver: bridge